Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -28,9 +28,16 @@ jobs:
       - name: Install dependencies
         run: go mod tidy
 
-      - name: Install expect tool (Linux/macOS)
-        if: runner.os != 'Windows'
-        run: sudo apt-get install expect
+      - name: Install expect tool (Linux)
+        if: runner.os == 'Linux'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y expect
+
+      - name: Install expect tool (macOS)
+        if: runner.os == 'macOS'
+        run: |
+          brew install expect || echo "Expect installation failed"
 
       - name: Install expect tool (Windows)
         if: runner.os == 'Windows'
@@ -75,7 +82,6 @@ jobs:
           send "123456\r"
           expect "Password entered => 123456"
           EOF
-
 
       - name: Run Choices Example
         run: |
